version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for PHP Packages
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
